#!/bin/bash

set -e

echo
echo

KEYMAPS="
	dm9records/lain:richdawe
	hs60/v2/ansi:richdawe
	hs60/v2/iso:richdawe
	keyhive/ut472:richdawe
	keyhive/ut472:richdawe2
	kiserdesigns/monorail2:richdawe
	mode/m256wh:richdawe
	neo/neo65/ansi_072:richdawe
	oxwich50:richdawe
	parallel/parallel_65/hotswap:richdawe
	ymdk/ymd62:richdawe
"

if [ -n "$1" ]; then
	KEYMAPS=
	for k in $*; do
		KEYMAPS="$KEYMAPS $1"
		shift
	done
fi

for k in $KEYMAPS; do
	kb=$(echo $k | cut -f 1 -d :)
	km=$(echo $k | cut -f 2 -d :)

	if [ -z "$kb" -o -z "$km" ]; then
		echo "Keymap format error: $k" 1>&2
		exit 1
	fi

	echo
	echo LINTING:
	echo qmk lint -kb $kb -km $km
	echo
	qmk lint -kb $kb -km $km

	echo
	echo COMPILING:
	echo qmk compile -kb $kb -km $km
	echo
	qmk compile -kb $kb -km $km
done
